GET http://localhost:8080/api/students/pageNum=1&pageSize=10&sortBy=fullName
Accept: */*
Cache-Control: no-cache

### Get List Student

POST http://localhost:8080/api/students
Content-Type: application/json

{
   "code": "PH09199",
   "fullName": "Hồng Tú",
   "address": "Thái Bình",
   "birthday": "2003-09-29",
   "class_id": "2"
}

### AddOrUpdate Student

GET http://localhost:8080/api/classes
Accept: */*
Cache-Control: no-cache

### Get List Class



POST http://localhost:8080/api/classes
Content-Type: application/json

{
   "id": 3,
   "name": "PT14303"
}

### AddOrUpdate Student