POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "hongtpph07122",
  "password": "context"
}

###
GET http://localhost:8080/api/logup
Accept: */*
Cache-Control: no-cache

###
